# CI build for release packages.

variables:
  UnityVersion: Unity2018.3.7f1
  MRTKVersion: 2.0.0

jobs:
- job: CIReleaseValidation
  pool:
    name: Analog On-Prem
    demands:
    - Unity2018.3.7f1  # variable expansion not allowed here
    - COG-UnityCache-WUS2-01
  steps:
  - template: templates/common.yml
  - template: templates/package.yml
  - template: templates/releasesigning.yml
  - template: templates/end.yml
